# Generated by Django 2.2.6 on 2020-06-30 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(max_length=200)),
                ('user_summary', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('login_id', models.CharField(max_length=45, null=True)),
                ('user_Id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, null=True)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(default='test@okkgrl.com', max_length=100)),
                ('department', models.CharField(max_length=45, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('hro', 'HRO'), ('pso', 'PSO'), ('hrm', 'HRM'), ('hos', 'HOS'), ('admin', 'Admin'), ('pm', 'PM')], default='user', max_length=6)),
                ('password', models.CharField(default='test', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='payroll_db',
            fields=[
                ('employee_id', models.CharField(max_length=45, null=True)),
                ('employee_name', models.CharField(max_length=45, null=True)),
                ('paye', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('CUG', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('loan', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('empl_pension', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('emplc', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('total_ded', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('gross_pay', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('incentive', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('net_pay', models.DecimalField(decimal_places=10, max_digits=45, null=True)),
                ('comment', models.TextField(max_length=500, null=True)),
                ('salary_month', models.CharField(choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('March', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER')], default='JANUARY', max_length=13, verbose_name='Salary month')),
                ('salary_year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='Salary year')),
                ('username', models.CharField(max_length=45, null=True)),
                ('position', models.CharField(max_length=45, null=True)),
                ('TNO', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_login')),
            ],
        ),
    ]
