# Generated by Django 2.2.6 on 2020-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(max_length=200)),
                ('user_summary', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('login_id', models.CharField(max_length=45, null=True)),
                ('user_Id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(default='test@okkgrl.com', max_length=100)),
                ('department', models.CharField(max_length=45, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('hro', 'HRO'), ('pso', 'PSO'), ('hrm', 'HRM'), ('hos', 'HOS'), ('admin', 'Admin'), ('pm', 'PM')], default='green', max_length=6)),
                ('password', models.CharField(default='test', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
