# Generated by Django 2.2.6 on 2020-06-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='login_title',
            new_name='login_id',
        ),
    ]
