# Generated by Django 2.2.6 on 2020-06-09 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200609_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 11, 46, 30, 244063), verbose_name='last login'),
        ),
    ]
