# Generated by Django 2.2.6 on 2020-06-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200625_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='username',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='payroll_db',
            name='salary_month',
            field=models.CharField(choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('March', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER')], default='user', max_length=13),
        ),
    ]
