# Generated by Django 2.2.6 on 2020-06-10 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200609_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=200)),
                ('login_content', models.TextField()),
                ('last_login', models.DateTimeField(default=datetime.datetime(2020, 6, 10, 3, 58, 57, 396289), verbose_name='last login')),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
