# Generated by Django 2.2.6 on 2020-06-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200625_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll_db',
            old_name='user_id',
            new_name='user_Id',
        ),
    ]
