# Generated by Django 2.2.6 on 2020-06-12 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200610_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(max_length=200)),
                ('user_summary', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='user_login',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 17, 45, 22, 224366), verbose_name='last login'),
        ),
    ]
