# Generated by Django 2.2.6 on 2020-06-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200625_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_login',
            old_name='user_Id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='payroll_db',
            name='user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_login', to_field='user_Id'),
        ),
    ]
