# Generated by Django 2.2.6 on 2020-06-13 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200612_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 13, 29, 49, 576670), verbose_name='last login'),
        ),
    ]
