# Generated by Django 2.2.6 on 2020-06-16 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200613_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user_login',
            name='login_content',
        ),
        migrations.AddField(
            model_name='user_login',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='email',
            field=models.CharField(default='test@okkgrl.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user_login',
            name='first_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user_login',
            name='last_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user_login',
            name='password',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AddField(
            model_name='user_login',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_login',
            name='login_id',
            field=models.CharField(max_length=45),
        ),
    ]
