# Generated by Django 2.2.6 on 2020-06-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200616_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='department',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user_login',
            name='role',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
